version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: compile artifacts and run tests
          command: gradle build

  deploy:
      docker:
        - image: hashicorp/terraform:full
      working_directory: ~/repo
      steps:
        - run:
            name: install aws cli
            command: |
              sudo apt get python-pip
              sudo pip install awscli

        - run:
            name: send compiled jar to s3
            command: aws s3 cp ./build/libs/mercury-ftp-1.0-SNAPSHOT.jar s3://mercury-terraform/build-artifacts/

        - restore_cache:
            keys:
              - terraform-v1-{{ checksum "terraform-plugins" }}
              - terraform-v1-

        - run:
            name: apply changes with terraform
            command: |
              cd infrastructure
              terraform init
              terraform apply -auto-approve

        - save_cache:
            paths:
              - ~/infrastructure/.terraform
            key: terraform-v1-{{ checksum "terraform-plugins" }}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

